### ISSUE TITLE
Different output formats

### ISSUE THREAD

**Issue by edenn-cyrebro** [alwashmi/MasterParser#1]
Is it possible to include different parser output formats in the project?
I'm talking about outputs that do not feature nested dictionaries.

Thanks for taking the time to read this issue, thank you for the great project!

**Comment by alwashmi** [comment]
Hi, apologies for late response. The repo is no longer maintained. We are working on a much better and more stable version of MasterParser and hoarder that allows csv and other formats. However, you may view the latest version released here for now: https://github.com/DFIRKuiper/Hoarder

**Comment by alwashmi** [comment]
Forgot to mention too the latest version woth hoarder produces mostly jsonl which might help.

**Comment by edenn-cyrebro** [comment]
You are amazing thanks!!!
________________________________
